name: Backend CI Pipeline

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle
        run: chmod +x backend/gradlew

      - name: Prepare application.properties
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          CHATPGT_API_URL: ${{ secrets.CHATPGT_API_URL }}
          CHATPGT_API_KEY: ${{ secrets.CHATPGT_API_KEY }}
        run: |
          envsubst < backend/src/main/resources/application.properties.template > backend/src/main/resources/application.properties
      

      - name: Build & Test with Gradle
        run: cd backend && ./gradlew clean build test

      - name: List build/libs directory
        working-directory: ./backend
        run: ls -l build/libs/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t blancjh/gymtinued-backend:latest backend/

      - name: Push Docker Image to Docker Hub
        run: docker push blancjh/gymtinued-backend:latest
